apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vs45k1pc5-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vs45k1pc5-go 
  name: vs45k1pc5-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vs45k1pc5-go 
